apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: da02-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-update-frequency: "15m"
    # Watch list with explicit 'latest' tags
    argocd-image-updater.argoproj.io/image-list: |
      admin-server=docker.io/vuhoabinhthachhoa/spring-petclinic-admin-server:latest,
      api-gateway=docker.io/vuhoabinhthachhoa/spring-petclinic-api-gateway:latest,
      config-server=docker.io/vuhoabinhthachhoa/spring-petclinic-config-server:latest,
      customers-service=docker.io/vuhoabinhthachhoa/spring-petclinic-customers-service:latest,
      discovery-server=docker.io/vuhoabinhthachhoa/spring-petclinic-discovery-server:latest,
      vets-service=docker.io/vuhoabinhthachhoa/spring-petclinic-vets-service:latest,
      visits-service=docker.io/vuhoabinhthachhoa/spring-petclinic-visits-service:latest

    argocd-image-updater.argoproj.io/admin-server.update-strategy: digest
    argocd-image-updater.argoproj.io/api-gateway.update-strategy: digest
    argocd-image-updater.argoproj.io/config-server.update-strategy: digest
    argocd-image-updater.argoproj.io/customers-service.update-strategy: digest
    argocd-image-updater.argoproj.io/discovery-server.update-strategy: digest
    #argocd-image-updater.argoproj.io/genai-service.update-strategy: digest
    argocd-image-updater.argoproj.io/vets-service.update-strategy: digest
    argocd-image-updater.argoproj.io/visits-service.update-strategy: digest

    # How to apply changes
    argocd-image-updater.argoproj.io/write-back-method: argocd

    argocd-image-updater.argoproj.io/admin-server.helm.image-path: services.admin-server.image
    argocd-image-updater.argoproj.io/api-gateway.helm.image-path: services.api-gateway.image
    argocd-image-updater.argoproj.io/config-server.helm.image-path: services.config-server.image
    argocd-image-updater.argoproj.io/customers-service.helm.image-path: services.customers-service.image
    argocd-image-updater.argoproj.io/discovery-server.helm.image-path: services.discovery-server.image
    #argocd-image-updater.argoproj.io/genai-service.helm.image-path: services.genai-service.image
    argocd-image-updater.argoproj.io/vets-service.helm.image-path: services.vets-service.image
    argocd-image-updater.argoproj.io/visits-service.helm.image-path: services.visits-service.image
spec:
  project: da02
  source:
    repoURL: https://github.com/OpsInUs/DA02-HelmRepo
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml
        - env/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true