apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: da02-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/webhook: "true"
    argocd-image-updater.argoproj.io/image-list: |
      admin-server=vuhoabinhthachhoa/spring-petclinic-admin-server:latest,
      api-gateway=vuhoabinhthachhoa/spring-petclinic-api-gateway:latest,
      config-server=vuhoabinhthachhoa/spring-petclinic-config-server:latest,
      customers-service=vuhoabinhthachhoa/spring-petclinic-customers-service:latest,
      discovery-server=vuhoabinhthachhoa/spring-petclinic-discovery-server:latest,
      vets-service=vuhoabinhthachhoa/spring-petclinic-vets-service:latest,
      visits-service=vuhoabinhthachhoa/spring-petclinic-visits-service:latest

    argocd-image-updater.argoproj.io/admin-server.update-strategy: digest
    argocd-image-updater.argoproj.io/api-gateway.update-strategy: digest
    argocd-image-updater.argoproj.io/config-server.update-strategy: digest
    argocd-image-updater.argoproj.io/customers-service.update-strategy: digest
    argocd-image-updater.argoproj.io/discovery-server.update-strategy: digest
    argocd-image-updater.argoproj.io/genai-service.update-strategy: digest
    argocd-image-updater.argoproj.io/vets-service.update-strategy: digest
    argocd-image-updater.argoproj.io/visits-service.update-strategy: digest

    argocd-image-updater.argoproj.io/write-back-method: argocd

    argocd-image-updater.argoproj.io/admin-server.helm.image-name: services.admin-server.image.repository
    argocd-image-updater.argoproj.io/api-gateway.helm.image-name: services.api-gateway.image.repository
    argocd-image-updater.argoproj.io/config-server.helm.image-name: services.config-server.image.repository
    argocd-image-updater.argoproj.io/customers-service.helm.image-name: services.customers-service.image.repository
    argocd-image-updater.argoproj.io/discovery-server.helm.image-name: services.discovery-server.image.repository
    argocd-image-updater.argoproj.io/genai-service.helm.image-name: services.genai-service.image.repository
    argocd-image-updater.argoproj.io/vets-service.helm.image-name: services.vets-service.image.repository
    argocd-image-updater.argoproj.io/visits-service.helm.image-name: services.visits-service.image.repository

    argocd-image-updater.argoproj.io/admin-server.helm.image-tag: services.admin-server.image.tag
    argocd-image-updater.argoproj.io/api-gateway.helm.image-tag: services.api-gateway.image.tag
    argocd-image-updater.argoproj.io/config-server.helm.image-tag: services.config-server.image.tag
    argocd-image-updater.argoproj.io/customers-service.helm.image-tag: services.customers-service.image.tag
    argocd-image-updater.argoproj.io/discovery-server.helm.image-tag: services.discovery-server.image.tag
    argocd-image-updater.argoproj.io/genai-service.helm.image-tag: services.genai-service.image.tag
    argocd-image-updater.argoproj.io/vets-service.helm.image-tag: services.vets-service.image.tag
    argocd-image-updater.argoproj.io/visits-service.helm.image-tag: services.visits-service.image.tag
spec:
  project: da02
  source:
    repoURL: https://github.com/OpsInUs/DA02-HelmRepo
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml
        - env/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true