apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: da02-dev
  namespace: argocd
  annotations:
    # Define images to watch
    argocd-image-updater.argoproj.io/image-list: >-
      admin-server=docker.io/vuhoabinhthachhoa/spring-petclinic-admin-server:latest,
      api-gateway=docker.io/vuhoabinhthachhoa/spring-petclinic-api-gateway:latest,
      config-server=docker.io/vuhoabinhthachhoa/spring-petclinic-config-server:latest,
      customers-service=docker.io/vuhoabinhthachhoa/spring-petclinic-customers-service:latest,
      discovery-server=docker.io/vuhoabinhthachhoa/spring-petclinic-discovery-server:latest,
      genai-service=docker.io/vuhoabinhthachhoa/spring-petclinic-genai-service:latest,
      vets-service=docker.io/vuhoabinhthachhoa/spring-petclinic-vets-service:latest,
      visits-service=docker.io/vuhoabinhthachhoa/spring-petclinic-visits-service:latest
    
    # Set update strategy for each service
    argocd-image-updater.argoproj.io/admin-server.update-strategy: digest
    argocd-image-updater.argoproj.io/api-gateway.update-strategy: digest
    argocd-image-updater.argoproj.io/config-server.update-strategy: digest
    argocd-image-updater.argoproj.io/customers-service.update-strategy: digest
    argocd-image-updater.argoproj.io/discovery-server.update-strategy: digest
    argocd-image-updater.argoproj.io/genai-service.update-strategy: digest
    argocd-image-updater.argoproj.io/vets-service.update-strategy: digest
    argocd-image-updater.argoproj.io/visits-service.update-strategy: digest
    
    # Use ArgoCD API for updates
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: da02  # Keep your existing project
  source:
    repoURL: https://github.com/OpsInUs/DA02-HelmRepo
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - env/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true