apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: da02-staging
  namespace: argocd
spec:
  project: da02
  source:
    repoURL: https://github.com/OpsInUs/DA02-HelmRepo
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml
        - env/staging/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true