apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: da02
  namespace: argocd
spec:
  description: Project for DA02 microservices
  sourceRepos:
    - https://github.com/OpsInUs/DA02-HelmRepo
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
